name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    # Runs at minute 0 past every 6th hour
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install and Run Cypress
        run: | 
          git config --global user.email "6973263+realvorl@users.noreply.github.com"
          git config --global user.name "(Vorl)-Bot"
          git pull
          git checkout gh-pages
          yarn 
          yarn cy-all
          git add .
          git commit -am "chore (ci): update e2e test results $(date +%s)"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/e2e/0-mine/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: chart
          path: ./cypress/e2e/0-mine/chart.html
          retention-days: 14
